name: smartleia-test-applet

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  applet_tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # Compilation tests
      - name: applet tests
        shell: bash
        run: |
          # 1) Get dependencies
          sudo apt-get install -y --no-install-recommends procps autoconf automake libtool m4 pkg-config help2man make gcc ant automake autotools-dev sudo wget gnupg software-properties-common maven git pcscd libpcsclite-dev opensc;
          # 2) Get JDK
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -;
          sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/;
          sudo apt-get update && sudo apt-get install --reinstall adoptopenjdk-8-hotspot;
          sudo update-java-alternatives -s adoptopenjdk-8-hotspot-amd64;
          # 3) Get Javacard SDKs
          cd sdks && git clone https://github.com/martinpaljak/oracle_javacard_sdks && mv oracle_javacard_sdks/jc303_kit ./ && mv oracle_javacard_sdks/jc305u3_kit/ /tmp/ && rm -rf oracle_javacard_sdks && cd -;
          # 4) Compile our applet
          make; 
          # 5) Clone jcardsim repository, compile and install
          git clone https://github.com/licel/jcardsim;
          cd jcardsim && export export JC_CLASSIC_HOME=/tmp/jc305u3_kit/ && mvn initialize && mvn clean install
          # 7) Clone vsmartcard, compile and install
          git clone https://github.com/frankmorgner/vsmartcard.git;
          cd vsmartcard/virtualsmartcard && autoreconf --verbose --install && ./configure --sysconfdir=/etc && make && sudo make install;
          # 8) Launch PCSCD
          pcscd -f &>/tmp/log_pcsc & echo "PCSCD launched";
          # 9) launch jcardsim
          #java -cp jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar:targettest/targettest.cap com.licel.jcardsim.remote.VSmartCard applet.cfg &>/tmp/log_jcardsim & echo "jcardsim launched!";
          java -cp jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar:targettest/targettest.cap com.licel.jcardsim.remote.VSmartCard applet.cfg &>/tmp/log_jcardsim & echo "jcardsim launched!";
          # Wait a bit for insertion
          sleep 2;
          echo "========= PCSCD log"     && cat /tmp/log_pcsc;
          echo "========= jcard sim log" && cat /tmp/log_jcardsim;
          
          # 10) Test our applet using APDUs
          opensc-tool -s 00A404000a45757477747536417080 -s 0001000000 -s 0002000d00 -s 0003000003010203  -s 000400050301020300 -s 000500ff00;
