name: smartleia-test-applet

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  applet_tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # Compilation tests
      - name: applet tests
        shell: bash
        run: |
          # 1) Get dependencies
          sudo apt-get install -y --no-install-recommends procps autoconf automake libtool m4 pkg-config help2man make gcc ant automake autotools-dev sudo wget gnupg software-properties-common maven git pcscd libpcsclite-dev opensc;
          # 2) Get JDK
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -;
          sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/;
          sudo apt-get update && sudo apt-get install --reinstall adoptopenjdk-8-hotspot;
          sudo update-java-alternatives -s adoptopenjdk-8-hotspot-amd64;
          # 3) Get Javacard SDKs
          cd sdks && git clone https://github.com/martinpaljak/oracle_javacard_sdks && mv oracle_javacard_sdks/jc303_kit ./ && mv oracle_javacard_sdks/jc305u3_kit/ /tmp/ && rm -rf oracle_javacard_sdks && cd -;
          # 4) Compile our applet
          make; 
          # 5) Clone jcardsim repository, compile and install
          git clone https://github.com/licel/jcardsim;
          cd jcardsim && export export JC_CLASSIC_HOME=/tmp/jc305u3_kit/ && mvn initialize && mvn clean install && cd -;
          # 7) Clone vsmartcard, compile and install
          git clone https://github.com/frankmorgner/vsmartcard.git;
          cd vsmartcard/virtualsmartcard && autoreconf --verbose --install && ./configure --sysconfdir=/etc && make && sudo make install && cd -;
          # 8) (re)Launch PCSCD
          sudo killall pcscd && sudo pcscd -fad &>/tmp/log_pcsc & echo "PCSCD launched";
          sleep 2;
          # 9) launch jcardsim
          java -cp jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar:targettest/targettest.jar com.licel.jcardsim.remote.VSmartCard applet.cfg &>/tmp/log_jcardsim & echo "jcardsim launched!";
          # Wait a bit for insertion
          sleep 2;
          echo "========= PCSCD log"     && cat /tmp/log_pcsc;
          echo "========= jcard sim log" && cat /tmp/log_jcardsim;          
          # 10) Test our applet using APDUs
          opensc-tool -l;
          # Install applet
          opensc-tool -s 80b80000110a45757477747536417080050000020F0F00;
          # Execute tests
          # Test APDU cases
          opensc-tool -s 00A404000a45757477747536417080 -s 0001000000 -s 0002000d00 -s 0003000003010203  -s 000400050301020300 -s 000500ff00 | tee /tmp/test_apdu_cases.apdu;
          cmp --silent /tmp/test_apdu_cases.apdu tests/test_apdu_cases.apdu || (echo "Test APDU cases failed!" && false);
          # Test AES128 enc
          opensc-tool -s 00A404000a45757477747536417080 -s 00110000102b7e151628aed2a6abf7158809cf4f3c -s 0015000000 -s 00120000106bc1bee22e409f96e93d7e117393172a -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes128_enc.apdu;
          cmp --silent /tmp/test_aes128_enc.apdu tests/test_aes128_enc.apdu || (echo "Test AES128 enc failed!" && false);
          # Test AES128 dec
          opensc-tool -s 00A404000a45757477747536417080 -s 00110000102b7e151628aed2a6abf7158809cf4f3c -s 0015000000 -s 001700000101 -s 00120000103ad77bb40d7a3660a89ecaf32466ef97 -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes128_dec.apdu;
          cmp --silent /tmp/test_aes128_dec.apdu tests/test_aes128_dec.apdu || (echo "Test AES128 dec failed!" && false);
          # Test AES192 enc
          opensc-tool -s 00A404000a45757477747536417080 -s 00110000188e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b -s 0015000000 -s 00120000106bc1bee22e409f96e93d7e117393172a -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes192_enc.apdu;
          cmp --silent /tmp/test_aes192_enc.apdu tests/test_aes192_enc.apdu || (echo "Test AES192 enc failed!" && false);
          # Test AES192 dec
          opensc-tool -s 00A404000a45757477747536417080 -s 00110000188e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b -s 0015000000 -s 001700000101 -s 0012000010bd334f1d6e45f25ff712a214571fa5cc -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes192_dec.apdu;
          cmp --silent /tmp/test_aes192_dec.apdu tests/test_aes192_dec.apdu || (echo "Test AES192 dec failed!" && false);
          # Test AES256 enc
          opensc-tool -s 00A404000a45757477747536417080 -s 0011000020603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4 -s 0015000000 -s 00120000106bc1bee22e409f96e93d7e117393172a -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes256_enc.apdu;
          cmp --silent /tmp/test_aes256_enc.apdu tests/test_aes256_enc.apdu || (echo "Test AES256 enc failed!" && false);
          # Test AES256 dec
          opensc-tool -s 00A404000a45757477747536417080 -s 0011000020603deb1015ca71be2b73aef0857d77811f352c073b6108d72d9810a30914dff4 -s 0015000000 -s 001700000101 -s 0012000010f3eed1bdb5d2a03c064b5a7e3db181f8 -s 0016000000 -s 0014000000 -s 0013000000 | tee /tmp/test_aes256_dec.apdu;
          cmp --silent /tmp/test_aes256_dec.apdu tests/test_aes256_dec.apdu || (echo "Test AES256 dec failed!" && false);
