name: smartleia-test-applet

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  vanilla_tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v2
      # Run actions
      # Compilation tests
      - name: applet tests
        shell: bash
        run: |
          # 1) Get dependencies
          sudo apt-get install -y --no-install-recommends procps autoconf automake libtool m4 pkg-config help2man make gcc gcc-arm-none-eabi kconfig-frontends ant automake autotools-dev sudo wget gnupg software-properties-common maven git;
          # 2) Get Javacard SDKs
          cd sdks && git clone https://github.com/martinpaljak/oracle_javacard_sdks && mv oracle_javacard_sdks/jc303_kit ./ && rm -rf oracle_javacard_sdks && cd -;
          # 2) Get JDK
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -;
          sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/;
          sudo apt-get update && sudo apt-get install adoptopenjdk-8-hotspot;
          update-java-alternatives -s adoptopenjdk-8-hotspot-amd64;
          # 3) Compile our applet
          make; 
          # 2) Clone jcardsim repository
          git clone https://github.com/licel/jcardsim;          
